python DRnavX.py base uno
python DRnavX.py uno due
python DRnavX.py due tre
python DRnavX.py tre tav1
python DRnavX.py tav1 tre
python DRnavX.py tre tav2
python DRnavX.py tav2 tre
python DRnavX.py tre due
python DRnavX.py due uno
python DRnavX.py uno base