image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 624.00193,    0.     ,  327.59452,
            0.     ,  627.70349,  236.33007,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.028596, -0.219766, 0.002488, -0.002293, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 619.04974,    0.     ,  326.77229,    0.     ,
            0.     ,  627.44934,  236.9841 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
