obstacle_range: 3 # 2.5
raytrace_range: 3.5 # 3.0

#footprint: [[0.13,0.2], [0.13, -0.2],[-0.13,-0.2],[-0.13,0.2]]
footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
#robot_radius: 0.14
#`e il raggio espresso in metri che circonda un oggetto e che viene suddiviso in aree
# di costo per ottimizzare la navigazione nei pressi degli ostacoli
inflation_radius: 0.25 # 0.15
cost_scaling_factor: 0.5
#
#holonomic robot: true
map_type: costmap
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
