obstacle_range: 2.5
raytrace_range: 3.0

#footprint: [[0.13,0.2], [0.13, -0.2],[-0.13,-0.2],[-0.13,0.2]]
robot_radius: 0.20
#`e il raggio espresso in metri che circonda un oggetto e che viene suddiviso in aree
# di costo per ottimizzare la navigazione nei pressi degli ostacoli
inflation_radius: 0.15
#
holonomic robot: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
