local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: false
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.05

  obstacle_range: 2.5
  raytrace_range: 3.0
  #footprint: '[]'
  robot_radius: 0.30
  # 
  inflation_radius: 0.60
  cost_scaling_factor: 5.0

  observation_sources: laser_scan_sensor 
  laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  
  obstacle_layer:
    enabled: true
    combination_method: 1
    footprint_clearing_enabled: false
    max_obstacle_height: 2.0
    obstacle_range: 3.0
    raytrace_range: 3.5

